### ISSUE TITLE
[Question] Basic Auth

### ISSUE THREAD

**Issue by bruhtus** [dundee/disk_usage_exporter#13]
Hello there, I am new to prometheus and I just take a look at [prometheus guides basic auth](https://prometheus.io/docs/guides/basic-auth/).

I tried the same in disk usage exporter config, more or less like this:
```yaml
basic_auth_users:
  admin: <password-hash>
analyzed-path: /var/www/media
dir-level: 1
```
but I still can access the endpoint without username and password.

I already restart the systemd service but there's no change.

So I want to make sure, is disk usage exporter support basic auth?
If it is, then how can we implement basic auth with disk usage exporter?
Thank you!
