### ISSUE TITLE
cost too much memory

### ISSUE THREAD

**Issue by Cosrider** [dundee/disk_usage_exporter#4]
i deploy  disk_usage_expoter in k8s cluster. I want to collect disk usage of dir  /var/lib/docker.

my ds is:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-usage-exporter
spec:
  selector:
    matchLabels:
      app: disk-usage-exporter
  template:
    metadata:
      labels:
        app: disk-usage-exporter
        name: disk-usage-exporter
      name: disk-usage-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: disk-usage-exporter
          args:
            - -p=/host/var
            - -l=0
          image: disk-usage-exporter:v0.2.0
          ports:
            - containerPort: 9995
              name: scrape
          volumeMounts:
            - mountPath: /host/var/lib/docker
              mountPropagation: HostToContainer
              name: docker
              readOnly: true
            - mountPath: /host/root
              name: root
              mountPropagation: HostToContainer
              readOnly: true
            - mountPath: /host/proc
              name: proc
      serviceAccountName: default
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /proc
            type: ""
          name: proc
        - hostPath:
            path: /var/lib/docker
            type: ""
          name: docker
        - hostPath:
            path: /
            type: ""
          name: root
```

i think the pods use too much  mem .

command ：kubectl  top  pod
```
disk-usage-exporter-h9d97                   363m          9248Mi          
disk-usage-exporter-jfh2p                     2457m        2106Mi          
disk-usage-exporter-wvx9c                   2886m        1659Mi  
```

when i curl podIP:9995/metrics , it takes seconds  to get metrics
```
[root@master]# curl 172.31.139.237:9995/metrics | grep var
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6470    0  6470    0     0    417      0 --:--:--  0:00:15 --:--:--  1449
node_disk_usage_bytes{path="/host/var"} 6.3816163328e+10
```

and the pod disk-usage-exporter-h9d97  which  cost mem shows  9248Mi   doesn't work, its log is:
```
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067910992, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067911312, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067911728, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067912048, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067912368, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067911632, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067914976, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067916296, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067915608, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067915928, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067918040, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067909112, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067915592, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067919008, free: 318873600"
time="2022-04-22T03:25:10Z" level=info msg="setting GC percent to 3, alloc: 8067919672, free: 318873600
```

can any one give some help?

**Comment by Cosrider** [comment]
@dundee

**Comment by dundee** [comment]
@Cosrider I have added explicit attempt to free OS memory. Could you try again with the version from master?

**Comment by Cosrider** [comment]
ok.

**Comment by Cosrider** [comment]
With limited resource
```
    resources:
      limits:
        cpu: "1"
        memory: 2000Mi
      requests:
        cpu: 100m
        memory: 100Mi
```

always OOM

```
# kubectl -n system-monitoring get pod  | grep disk 
disk-usage-exporter-4jts8                   0/1     CrashLoopBackOff   215        20h
disk-usage-exporter-nk7sx                   0/1     CrashLoopBackOff   169        20h
disk-usage-exporter-pg782                   1/1     Running            154        20h
```

without resource limits：

```
➜  ~ kubectl -n system-monitoring  top pod | grep disk
disk-usage-exporter-7smnl                   3006m        1647Mi          
disk-usage-exporter-lf7hs                      12m          156Mi           
disk-usage-exporter-qchqc                   1087m        2109Mi 
```

is it possible to lower cpu and memory cost when  analysing ?
